Repository ONSdigital/ssdc-rm-ddl, pull requests merged in 2024-05, with the labels that each got.

#195 Updated GHActions
  .github/workflows/checks-and-tests.yml
Labels: patch

#197 SDCSRM-368 removing WCIS templates and resetting ddl
  dev-common-postgres-image/init.sql
  groundzero_ddl/ddl_version.sql
  groundzero_ddl/packcode_templates/email_templates.sql
  patch_database.py
  patches/1000_update_CRIS_export_file_templates.sql
  patches/100_add_indexs.sql
  patches/1100_add_reminder_with_uacs_templates.sql
  patches/1200_update_uac_replacement_template.sql
  patches/1300_delete_templates.sql
  patches/1400_add_WCIS_email_templates.sql
  patches/1500_add_notify_service_ref_column_and_seed_values.sql
  patches/1600_add_not_null_constraint_to_notify_service_ref.sql
  patches/1700_add_type_into_columns.sql
  patches/200_add_support_permissions.sql
  patches/300_add_create_eq_flush_action_rule_permission.sql
  patches/400_add_packcode_templates.sql
  patches/500_add_fulfilment_permissions.sql
  patches/600_add_new_app_user.sql
  patches/700_update_export_file_suppliers.sql
  patches/800_insert_cris_templates.sql
  patches/900_support_actions_allow_email_fulfilments_permission.sql
  patches/rollback/1000_update_CRIS_export_file_templates.sql
  patches/rollback/100_add_indexs.sql
  patches/rollback/1100_add_reminder_with_uacs_template.sql
  patches/rollback/1200_update_uac_replacement_template.sql
  patches/rollback/1300_delete_templates.sql
  patches/rollback/1400_add_WCIS_email_templates.sql
  patches/rollback/1500_add_notify_service_ref_column_and_seed_values.sql
  patches/rollback/1600_add_not_null_constraint_to_notify_service_ref.sql
  patches/rollback/1700_add_type_into_columns.sql
  patches/rollback/200_add_support_permissions.sql
  patches/rollback/300_add_create_eq_flush_action_rule_permission.sql
  patches/rollback/400_add_packcode_templates.sql
  patches/rollback/500_add_fulfilment_permissions.sql
  patches/rollback/600_add_new_app_user.sql
  patches/rollback/700_update_export_file_suppliers.sql
  patches/rollback/800_insert_cris_templates.sql
  patches/rollback/900_support_actions_allow_email_fulfilments_permission.sql
Labels: feature

#198 Added new column to action_rule to store number of cases selected for…
  dev-common-postgres-image/init.sql
  groundzero_ddl/casev3.sql
  groundzero_ddl/ddl_version.sql
  patch_database.py
  patches/100_add_selected_case_count.sql
  patches/rollback/100_add_selected_case_count.sql
  ssdc-rm-common-entity-model/pom.xml
  ssdc-rm-common-entity-model/src/main/java/uk/gov/ons/ssdc/common/model/entity/ActionRule.java
Labels: feature, schema change

#199 Update Postgres version in dev Dockerfile
  dev-common-postgres-image/Dockerfile
Labels: patch
