Repository ONSdigital/ssdc-rm-ddl, pull requests merged in 2024-07, with the labels that each got.

#205 SDCSRM-542 Dependabot Security Only PRs
  .github/dependabot.yml
Labels: patch

#213 Dependabot ignore fix
  .github/dependabot.yml
Labels: patch

#204 Productionise action rule status
  dev-common-postgres-image/init.sql
  groundzero_ddl/casev3.sql
  groundzero_ddl/ddl_version.sql
  patch_database.py
  patches/400_add_action_rule_status.sql
  patches/rollback/400_add_action_rule_status.sql
  ssdc-rm-common-entity-model/pom.xml
  ssdc-rm-common-entity-model/src/main/java/uk/gov/ons/ssdc/common/model/entity/ActionRule.java
  ssdc-rm-common-entity-model/src/main/java/uk/gov/ons/ssdc/common/model/entity/ActionRuleStatus.java
Labels: feature

#214 SDCSRM-520 Re-gen dev postgres init DDL
  dev-common-postgres-image/init.sql
Labels: patch

#215 SDCSRM-577 Make action rule status non-nullable
  dev-common-postgres-image/init.sql
  groundzero_ddl/casev3.sql
  groundzero_ddl/ddl_version.sql
  patch_database.py
  patches/500_set_action_rule_status_non_nullable.sql
  patches/rollback/500_set_action_rule_status_non_nullable.sql
  ssdc-rm-common-entity-model/pom.xml
  ssdc-rm-common-entity-model/src/main/java/uk/gov/ons/ssdc/common/model/entity/ActionRule.java
Labels: patch, schema change

#216 Removed codecov
  .github/workflows/checks-and-tests.yml
Labels: patch
